kind: Deployment
apiVersion: apps/v1
metadata:
  name: relay
  namespace: cardano
  labels:
    app: relay
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      securityContext:
        runAsUser: 1001
      containers:
        - name: relay
          image: dshiell15/cardano-node:1.26.0
          args: ["run", "--topology", "/config/mainnet-topology.json", "--database-path", "/data/db", "--socket-path", "/data/db/node.socket", "--port", "3001", "--config", "/config/mainnet-config.json"]   
          volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /config
            readOnly: true
          ports:
          - containerPort: 3001
          securityContext:
            allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "app"
                     operator: In
                     values:
                     - producer
               topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: local-path-2
      - name: config
        configMap:
          name: configs

