kind: Deployment
apiVersion: apps/v1
metadata:
  name: cardano-relay
  namespace: cardano
  labels:
    app: relay
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: relay
  template:
    metadata:
      labels:
        app: relay
    spec:
      containers:
        - name: cardano-relay
          image: dshiell15/cardano-node:1.26.0
	  command: ["run", "--topology path/to/mainnet-topology.json", "--database-path", "path/to/db", "--socket-path", "path/to/db/node.socket", "--host-addr", "x.x.x.x", "--port", "3001", "--config", "path/to/mainnet-config.json"]   
          volumeMounts:
          - name: data
            mountPath: /data
	  ports:
	  - containerPort: 3001
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: local-path-2