apiVersion: batch/v1
kind: Job
metadata:
  name: generate-pool-keys
  namespace: cardano
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      labels:
        job-name: generate-pool-keys
    spec:
      restartPolicy: Never
      volumes:
        - name: keys
          emptyDir: {}
        - name: config
          configMap:
            name: configs
      initContainers:
      - name: payment-keys
        image: dshiell15/cardano-node:1.26.2
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: ["cardano-cli", "address", "key-gen", "--verification-key-file", "payment.vkey", "--signing-key-file", "payment.skey"]
      - name: payment-address
        image: dshiell15/cardano-node:1.26.2
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: ["cardano-cli", "address", "build", "--payment-verification-key-file", "payment.vkey", "--out-file", "payment.addr", "--mainnet"]
      - name: cold-keys
        image: dshiell15/cardano-node:1.26.2
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: ["cardano-cli", "node", "key-gen", "--cold-verification-key-file", "cold.vkey", "--cold-signing-key-file", "cold.skey", "--operational-certificate-issue-counter-file", "cold.counter"]
      - name: vrf-keys
        image: dshiell15/cardano-node:1.26.2
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: ["cardano-cli", "node", "key-gen-VRF", "--verification-key-file", "vrf.vkey", "--signing-key-file", "vrf.skey"]
      - name: kes-keys
        image: dshiell15/cardano-node:1.26.2
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: ["cardano-cli", "node", "key-gen-KES", "--verification-key-file", "kes.vkey", "--signing-key-file", "kes.skey"]
      - name: operational-certificate
        image: dshiell15/cardano-node:1.26.2
        env:
        - name: KES_PERIOD
          valueFrom:
            configMapKeyRef:
              name: kesperiod
              key: kesPeriod
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: ["cardano-cli", "node", "issue-op-cert", "--kes-verification-key-file", "kes.vkey", "--cold-signing-key-file", "cold.skey", "--operational-certificate-issue-counter-file", "cold.counter", "--kes-period", "$(KES_PERIOD)", "--out-file", "node.cert" ]
      containers:
      - name: export-keys
        image: alpine
        volumeMounts:
          - name: keys
            mountPath: /keys
        workingDir: /keys
        command: [/bin/sh, -c]
        args:
          - |
            ls -l
            echo "Ready for download"
            echo "Sleeping to allow files to be exported with 'kubectl cp'"
            trap 'exit 255' SIGTERM
            sleep 10
            echo "Exiting"
  backoffLimit: 0