apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-100G
  namespace: cardano
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
 ---
 apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-400G
  namespace: cardano
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 400Gi