apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: relay-pvc
  namespace: cardano
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: producer-pvc
  namespace: cardano
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
