kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: relay
  namespace: cardano
  labels:
    role: relay
    app: cardano-mainnet-node
spec:
  serviceName: relay
  replicas: 2
  selector:
    matchLabels:
      role: relay
      app: cardano-mainnet-node
  template:
    metadata:
      labels:
        role: relay
        app: cardano-mainnet-node
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '12798'
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: relay
        image: dshiell15/cardano-node:1.26.2
        env:
        - name: CARDANO_NODE_SOCKET_PATH
          value: "/ipc/socket"
        args: ["run", "--topology", "/config/mainnet-relay-topology.json", "--database-path", "/data/db", "--socket-path", $(CARDANO_NODE_SOCKET_PATH), "--host-addr", "0.0.0.0", "--port", "3001", "--config", "/config/mainnet-config.json"]
        livenessProbe:
          exec:
            command: ["cardano-cli", "query", "tip", "--mainnet"]
          initialDelaySeconds: 5
          periodSeconds: 30
        startupProbe:
          exec:
            command: ["cardano-cli", "query", "tip", "--mainnet"]
          failureThreshold: 200
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["cardano-cli", "query", "tip", "--mainnet"]
          failureThreshold: 200
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
        - name: ipc
          mountPath: /ipc
        - name: config
          mountPath: /config
          readOnly: true
        ports:
        - containerPort: 3001
        - containerPort: 12798
        securityContext:
          allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "role"
                     operator: In
                     values:
                     - producer
               topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: ipc
        emptyDir:
          medium: Memory
      - name: config
        configMap:
          name: configs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 30Gi
