kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: relay
  namespace: cardano
  labels:
    role: relay
spec:
  serviceName: relay
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      role: relay
  template:
    metadata:
      labels:
        role: relay
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1001
      containers:
        - name: relay
          image: dshiell15/cardano-node:1.25.1
          env:
          - name: CARDANO_NODE_SOCKET_PATH
            value: "/ipc/socket"
          args: ["run", "--topology", "/config/mainnet-relay-topology.json", "--database-path", "/data/db", "--socket-path", $(CARDANO_NODE_SOCKET_PATH), "--host-addr", "0.0.0.0", "--port", "3001", "--config", "/config/mainnet-config.json"]   
          volumeMounts:
          - name: data
            mountPath: /data
	  - name: ipc
            mountPath: /ipc
          - name: config
            mountPath: /config
            readOnly: true
          ports:
          - containerPort: 3001
          securityContext:
            allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "app"
                     operator: In
                     values:
                     - producer
               topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: ipc
        emptyDir:
          medium: MemorypersistentVolumeClaim:
      - name: config
        configMap:
          name: configs
    volumeClaimTemplates:
    - metadata:
        name: data
      spec:
	accessModes: [ "ReadWriteOnce" ]
	storageClassName: "longhorn"
	resources:
	  requests:
	    storage: 50Gi
