kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: relay
  namespace: cardano
  labels:
    role: relay
spec:
  serviceName: relay
  replicas: 4
  selector:
    matchLabels:
      role: relay
  template:
    metadata:
      labels:
        role: relay
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: topology-updater
          image: dshiell15/cardano-topology-updater
          env:
          - name: CNODE_HOSTNAME
            value: "rpi-cardano-pool.dyndns.org"
          - name: CNODE_PORT
            value: 3001
          - name: EKG_TIMEOUT
            value: 3
          - name: EKG_HOST
            value: 127.0.0.1
          - name: EKG_PORT
            value: 12788
          - name: GENESIS_JSON
            value: "/config/mainnet-shelley-genesis.json"
          - name: LOG_DIR
            value: "/logs"
          - name: MAX_PEERS
            value: 20
          - CUSTOM_PEERS
            value: "producer-0.cardano.svc.cluster.local:3001:1"
          volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /config
            readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
       - name: relay
          image: dshiell15/cardano-node:1.26.1
          env:
          - name: CARDANO_NODE_SOCKET_PATH
            value: "/ipc/socket"
          args: ["run", "--topology", "/config/mainnet-relay-topology.json", "--database-path", "/data/db", "--socket-path", $(CARDANO_NODE_SOCKET_PATH), "--host-addr", "0.0.0.0", "--port", "3001", "--config", "/config/mainnet-config.json"]   
          volumeMounts:
          - name: data
            mountPath: /data
          - name: ipc
            mountPath: /ipc
          - name: config
            mountPath: /config
            readOnly: true
          ports:
          - containerPort: 3001
          - containerPort: 12798
          securityContext:
            allowPrivilegeEscalation: false
      affinity:
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "role"
                     operator: In
                     values:
                     - producer
               topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: ipc
        emptyDir:
          medium: Memory
      - name: config
        configMap:
          name: configs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 20Gi
