apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: cardano
spec:
  type: NodePort
  selector:
    app: relay
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 32635
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: cardano
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001