apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cardano-mainnet-node-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  namespaceSelector:
    any: true
    #matchNames:
    #  - cardano
  selector:
    matchLabels:
      app: cardano-mainnet-node