apiVersion: v1
kind: Service
metadata:
  name: relay
  namespace: cardano
spec:
  type: LoadBalancer
  selector:
    role: relay
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: relay-metrics
  namespace: cardano
spec:
  selector:
    role: relay
  ports:
    - name: prom
      protocol: TCP
      port: 12798
      targetPort: 12798
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: cardano
spec:
  selector:
    role: producer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001